# Get all people
GET http://localhost:3001/api/persons

# Get specific person (exists)
GET http://localhost:3001/api/persons/5ee028f9dd1d311d67b1c215

# Get specific person (DNE)
GET http://localhost:3001/api/persons/5ee028f9dd1d311d67b1c216

# Get specific person (DNE)
GET http://localhost:3001/api/persons/5

# Delete arbitrary person
DELETE http://localhost:3001/api/persons/5ee02f48ea148228a954dbb5

# Delete non-existant person
DELETE http://localhost:3001/api/persons/2

# Replace number
PUT http://localhost:3001/api/persons/5ee02f11b008ff283d5edc46
Content-Type: application/json

{
    "name": "Bigboi",
    "number": "456"
}

# Create a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bigboi",
    "number": "123456"
}